CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260524015313_InitialServiceRequestSchema') THEN
    CREATE TABLE service_requests (
        id text NOT NULL,
        title text NOT NULL,
        category text NOT NULL,
        priority text NOT NULL,
        description text NOT NULL,
        requester_name text NOT NULL,
        requester_email text NOT NULL,
        impact_details text,
        status text NOT NULL,
        created_at timestamp with time zone NOT NULL,
        sla_due_at timestamp with time zone NOT NULL,
        assignee_name text,
        resolution_notes text,
        CONSTRAINT "PK_service_requests" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260524015313_InitialServiceRequestSchema') THEN
    CREATE TABLE service_request_activity (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        service_request_id text NOT NULL,
        type text NOT NULL,
        occurred_at timestamp with time zone NOT NULL,
        description text NOT NULL,
        CONSTRAINT "PK_service_request_activity" PRIMARY KEY (id),
        CONSTRAINT "FK_service_request_activity_service_requests_service_request_id" FOREIGN KEY (service_request_id) REFERENCES service_requests (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260524015313_InitialServiceRequestSchema') THEN
    CREATE TABLE service_request_comments (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        service_request_id text NOT NULL,
        author_name text NOT NULL,
        body text NOT NULL,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_service_request_comments" PRIMARY KEY (id),
        CONSTRAINT "FK_service_request_comments_service_requests_service_request_id" FOREIGN KEY (service_request_id) REFERENCES service_requests (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260524015313_InitialServiceRequestSchema') THEN
    CREATE INDEX "IX_service_request_activity_service_request_id" ON service_request_activity (service_request_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260524015313_InitialServiceRequestSchema') THEN
    CREATE INDEX "IX_service_request_comments_service_request_id" ON service_request_comments (service_request_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260524015313_InitialServiceRequestSchema') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260524015313_InitialServiceRequestSchema', '10.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260524015336_AddServiceRequestStoredProcedures') THEN
    CREATE OR REPLACE FUNCTION opsledger_create_service_request(
        p_id TEXT,
        p_title TEXT,
        p_category TEXT,
        p_priority TEXT,
        p_description TEXT,
        p_requester_name TEXT,
        p_requester_email TEXT,
        p_impact_details TEXT,
        p_status TEXT,
        p_created_at TIMESTAMPTZ,
        p_sla_due_at TIMESTAMPTZ
    )
    RETURNS VOID
    LANGUAGE plpgsql
    AS $$
    BEGIN
        INSERT INTO service_requests (
            id,
            title,
            category,
            priority,
            description,
            requester_name,
            requester_email,
            impact_details,
            status,
            created_at,
            sla_due_at
        )
        VALUES (
            p_id,
            p_title,
            p_category,
            p_priority,
            p_description,
            p_requester_name,
            p_requester_email,
            p_impact_details,
            p_status,
            p_created_at,
            p_sla_due_at
        );

        INSERT INTO service_request_activity (
            service_request_id,
            type,
            occurred_at,
            description
        )
        VALUES (
            p_id,
            'Created',
            p_created_at,
            'Service request created.'
        );
    END;
    $$;

    CREATE OR REPLACE FUNCTION opsledger_assign_service_request(
        p_id TEXT,
        p_assignee_name TEXT,
        p_changed_at TIMESTAMPTZ
    )
    RETURNS VOID
    LANGUAGE plpgsql
    AS $$
    BEGIN
        UPDATE service_requests
        SET
            assignee_name = p_assignee_name,
            status = 'InProgress'
        WHERE id = p_id;

        IF NOT FOUND THEN
            RAISE EXCEPTION 'Service request % was not found.', p_id;
        END IF;

        INSERT INTO service_request_activity (
            service_request_id,
            type,
            occurred_at,
            description
        )
        VALUES (
            p_id,
            'Assigned',
            p_changed_at,
            'Assigned to ' || p_assignee_name || '.'
        );
    END;
    $$;

    CREATE OR REPLACE FUNCTION opsledger_resolve_service_request(
        p_id TEXT,
        p_resolution_notes TEXT,
        p_changed_at TIMESTAMPTZ
    )
    RETURNS VOID
    LANGUAGE plpgsql
    AS $$
    BEGIN
        UPDATE service_requests
        SET
            resolution_notes = p_resolution_notes,
            status = 'Resolved'
        WHERE id = p_id;

        IF NOT FOUND THEN
            RAISE EXCEPTION 'Service request % was not found.', p_id;
        END IF;

        INSERT INTO service_request_activity (
            service_request_id,
            type,
            occurred_at,
            description
        )
        VALUES (
            p_id,
            'Resolved',
            p_changed_at,
            'Request resolved.'
        );
    END;
    $$;

    CREATE OR REPLACE FUNCTION opsledger_add_service_request_comment(
        p_id TEXT,
        p_author_name TEXT,
        p_body TEXT,
        p_created_at TIMESTAMPTZ
    )
    RETURNS VOID
    LANGUAGE plpgsql
    AS $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM service_requests
            WHERE id = p_id
        ) THEN
            RAISE EXCEPTION 'Service request % was not found.', p_id;
        END IF;

        INSERT INTO service_request_comments (
            service_request_id,
            author_name,
            body,
            created_at
        )
        VALUES (
            p_id,
            p_author_name,
            p_body,
            p_created_at
        );

        INSERT INTO service_request_activity (
            service_request_id,
            type,
            occurred_at,
            description
        )
        VALUES (
            p_id,
            'CommentAdded',
            p_created_at,
            'Comment added by ' || p_author_name || '.'
        );
    END;
    $$;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260524015336_AddServiceRequestStoredProcedures') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260524015336_AddServiceRequestStoredProcedures', '10.0.8');
    END IF;
END $EF$;
COMMIT;

