// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpsLedger.Infrastructure.Persistence;

#nullable disable

namespace OpsLedger.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OpsLedgerDbContext))]
    [Migration("20260524015336_AddServiceRequestStoredProcedures")]
    partial class AddServiceRequestStoredProcedures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OpsLedger.Infrastructure.Persistence.Entities.RequestActivityRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("ServiceRequestId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_request_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ServiceRequestId");

                    b.ToTable("service_request_activity", (string)null);
                });

            modelBuilder.Entity("OpsLedger.Infrastructure.Persistence.Entities.RequestCommentRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("author_name");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ServiceRequestId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_request_id");

                    b.HasKey("Id");

                    b.HasIndex("ServiceRequestId");

                    b.ToTable("service_request_comments", (string)null);
                });

            modelBuilder.Entity("OpsLedger.Infrastructure.Persistence.Entities.ServiceRequestRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AssigneeName")
                        .HasColumnType("text")
                        .HasColumnName("assignee_name");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImpactDetails")
                        .HasColumnType("text")
                        .HasColumnName("impact_details");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("priority");

                    b.Property<string>("RequesterEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("requester_email");

                    b.Property<string>("RequesterName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("requester_name");

                    b.Property<string>("ResolutionNotes")
                        .HasColumnType("text")
                        .HasColumnName("resolution_notes");

                    b.Property<DateTimeOffset>("SlaDueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sla_due_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("service_requests", (string)null);
                });

            modelBuilder.Entity("OpsLedger.Infrastructure.Persistence.Entities.RequestActivityRecord", b =>
                {
                    b.HasOne("OpsLedger.Infrastructure.Persistence.Entities.ServiceRequestRecord", null)
                        .WithMany("Activity")
                        .HasForeignKey("ServiceRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpsLedger.Infrastructure.Persistence.Entities.RequestCommentRecord", b =>
                {
                    b.HasOne("OpsLedger.Infrastructure.Persistence.Entities.ServiceRequestRecord", null)
                        .WithMany("Comments")
                        .HasForeignKey("ServiceRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpsLedger.Infrastructure.Persistence.Entities.ServiceRequestRecord", b =>
                {
                    b.Navigation("Activity");

                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
